export const FETCH_LOGIN = 'FETCH_LOGIN'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'

export const FETCH_LOGOUT = 'FETCH_LOGOUT'
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOUGOUT_SUCCESS'
export const FETCH_LOGOUT_ERROR = 'FETCH_LOGOUT_ERROR'

export const SET_COOKIE_ANSWER = 'SET_COOKIE_ANSWER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_IS_CONNECTED = 'SET_IS_CONNECTED'
